name: CI

on:
  push:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Git checkout@v3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8.14.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: check changeset update
        run: pnpm changeset status --since=origin/master
